#Theoretical Questions

#### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans-1. **NUMPY**

1. The Powerhouse of Scientific Computing in Python.

2. NumPy, short for Numerical Python, is a fundamental library for scientific computing and data analysis in Python.

3. It provides efficient array manipulation and mathematical operations, significantly enhancing Python's capabilities for numerical computations.

### Key Purposes and Advantages:

1. Efficient Array Operations:

* **N-dimensional Arrays:** NumPy introduces the ndarray
object, a versatile data structure for representing arrays of any dimension. This enables efficient handling of multidimensional data, such as images, matrices, and tensors.

* **Vectorization:** NumPy allows you to perform operations on entire arrays element-wise, without the need for explicit loops.This vectorization significantly speeds up computations, especially for large datasets.

2. Broad Range of Mathematical Functions:

* NumPy offers a rich collection of mathematical functions, including trigonometric, logarithmic, exponential, and statistical functions.These functions are optimized for performance and can be applied to arrays efficiently.

3. Linear Algebra Operations:

* NumPy provides powerful linear algebra routines, such as matrix multiplication, inversion, and eigenvalue decomposition. These operations are essential for various scientific and engineering applications.

4. Random Number Generation:

* NumPy's random number generation capabilities are crucial for simulations, statistical modeling, and machine learning. It offers a variety of distributions, including uniform, normal, and Poisson.

5. Integration with Other Libraries:

* NumPy serves as the foundation for many other scientific Python libraries, such as SciPy, Pandas, Matplotlib, and scikit-learn.This seamless integration enables a comprehensive data analysis and machine learning workflow.

**How NumPy Enhances Python's Numerical Capabilities:**

1. **Performance:** NumPy's efficient array operations and vectorization significantly improve the speed of numerical computations compared to traditional Python loops.

2. **Conciseness**: NumPy's concise syntax and powerful functions allow you to express complex mathematical operations in a few lines of code.

3. **Flexibility:** NumPy's versatile ndarray object can be used to represent various data structures, making it suitable for a wide range of applications.

4. **Integration:** NumPy's seamless integration with other scientific Python libraries enables a powerful and flexible ecosystem for data analysis and scientific computing.

* By leveraging NumPy, you can efficiently handle large datasets, perform complex mathematical operations, and visualize data effectively, making it an indispensable tool for researchers, data scientists, and engineers.















#### 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Ans-2. **np.mean() vs. np.average() in NumPy**

While both functions are used to calculate averages, they have subtle differences in their functionality:

1. np.mean()

Purpose: Calculates the arithmetic mean of an array.



In [1]:
#Usage:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print(mean_value)

3.0


2. np.average()

Purpose: Calculates the weighted average of an array

In [2]:
#usage:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
weights = np.array([2, 1, 3, 1, 2])
weighted_mean = np.average(arr, weights=weights)

####When to Use Which:

1. **np.mean():**

* Use when you want to calculate the simple arithmetic mean of an array.

* Ideal for scenarios where all data points have equal importance.

2. **np.average():**

* Use when you want to calculate a weighted average, where different data points have different levels of importance.

* Useful in statistical analysis, machine learning, and other fields where certain data points might be more significant than others.

* In Conclusion:

Both functions are valuable tools in your NumPy toolkit. Choose np.mean() for straightforward arithmetic means and np.average() for more nuanced calculations involving weighted averages. By understanding their distinctions, you can effectively apply them to your data analysis tasks.




#### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans-3. **Reversing NumPy Arrays**

NumPy provides several methods to reverse arrays along specific axes. Here are the primary approaches:

1. **Using [::-1] Indexing:**

This simple slicing technique is effective for reversing arrays along a single axis.

In [4]:
# 1DArray
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

# 2DArray

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr_2d = np.flip(arr_2d)

[5 4 3 2 1]


2. **Using np.flip():**

This function provides more flexibility, allowing you to specify the axis or axes along which to reverse.

In [9]:
reversed_arr_2d = np.flip(arr_2d, axis=1)

**Choosing the Right Method:**

1. **Simple Reversal:** [::-1] indexing is straightforward for basic reversals.

2. **Complex Reversals or Multiple Axes:** np.flip() offers more control and flexibility.

By understanding these techniques, you can effectively manipulate NumPy arrays to suit your specific data analysis and computational needs.









#### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Ans-4. **Determining Data Types in NumPy Arrays**

In NumPy, you can determine the data type of elements in an array using the dtype attribute. Here's a simple example:

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int64


This will print the data type of the elements, which in this case is int32.

* Importance of Data Types in Memory Management and Performance

Data types play a crucial role in NumPy arrays, significantly impacting memory usage and computational efficiency. Here's why:

1. **Memory Efficiency:**

* Smaller Data Types, Less Memory: By choosing appropriate data types, you can reduce the memory footprint of your arrays. For instance, using int16 instead of int32 for integers that fit within a 16-bit range can halve the memory consumption.

* Efficient Memory Layout: NumPy arrays are stored in contiguous memory blocks, allowing for efficient memory access and vectorized operations. The data type determines the size of each element, influencing the overall memory layout.

2. **Computational Performance:**

* Optimized Operations: NumPy operations are highly optimized for specific data types. Using the correct data type can lead to significant performance improvements, especially for numerical computations.

* Vectorization: Vectorized operations, a core strength of NumPy, rely on efficient data type handling to achieve high performance.

* Hardware-Specific Optimizations: Modern processors often have specialized instructions for specific data types. By aligning data types with hardware capabilities, you can further boost performance.

#### Key Considerations:

1. Choose the Right Data Type: Select the smallest data type that can accurately represent your data. For example, if your integers are within a small range, int8 or int16 might be sufficient.

2. Be Mindful of Precision: While smaller data types can save memory, they may also reduce precision. If precision is critical, consider using larger data types like float64.

3. Leverage NumPy's Data Type Conversion: NumPy provides functions like astype to convert arrays to different data types. Use this carefully, as it can involve data copying and potential precision loss.

By understanding the importance of data types and making informed choices, you can optimize your NumPy arrays for both memory efficiency and computational performance.








#### 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans-5. **ndarrays in NumPy**

* NumPy's ndarray (n-dimensional array) is a fundamental data structure that represents a collection of elements, all of the same type, arranged in a multidimensional grid. It's the cornerstone of numerical computing in Python, offering significant advantages over standard Python lists in terms of performance and functionality.

#### Key Features of ndarrays:

1. Homogeneous Data Type: All elements in an ndarray must be of the same data type (e.g., int32, float64, bool). This homogeneity allows for efficient memory allocation and optimized operations.

2. Multidimensional: ndarrays can have any number of dimensions, from 0D (scalar) to nD (n-dimensional). This flexibility enables the representation of various mathematical objects like vectors, matrices, and tensors.

3. Efficient Memory Layout: Elements in an ndarray are stored in contiguous memory blocks, promoting efficient memory access and cache utilization.

4. Vectorized Operations: NumPy supports vectorized operations, allowing you to perform element-wise operations on entire arrays without explicit loops. This significantly speeds up computations.

5. Broadcasting: NumPy's broadcasting rules enable operations between arrays of different shapes, as long as certain conditions are met. This feature simplifies many mathematical operations.

6. Indexing and Slicing: Powerful indexing and slicing mechanisms allow you to access and manipulate specific elements or subsets of an array.

7. Ufuncs: Universal functions (ufuncs) provide efficient element-wise operations on arrays, including arithmetic, trigonometric, and logical operations.

* In essence, ndarrays offer a more efficient and powerful way to work with numerical data in Python. Their homogeneous data type, contiguous memory layout, vectorized operations, and broadcasting capabilities make them the preferred choice for numerical computations.




#### 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans-6. NumPy Arrays vs. Python Lists: A Performance Deep Dive

When it comes to large-scale numerical operations, NumPy arrays offer significant performance advantages over standard Python lists. Let's delve into the reasons behind this:

1. **Homogeneous Data Type:**

* NumPy: All elements in a NumPy array must be of the same data type, leading to efficient memory allocation and optimized operations.

* Python Lists: Python lists can store elements of different data types, which requires additional overhead for type checking and memory management.

2. **Contiguous Memory Layout:**

* NumPy: NumPy arrays store elements in contiguous memory blocks, allowing for efficient memory access and cache utilization.

* Python Lists: Python lists store elements in non-contiguous memory locations, which can lead to slower access times, especially when iterating over large datasets.

3. **Vectorized Operations:**

* NumPy: NumPy supports vectorized operations, enabling element-wise operations on entire arrays without explicit loops. This significantly reduces the overhead of Python's interpreter and leverages hardware-level optimizations.

* Python Lists: Python lists require explicit loops for element-wise operations, which can be significantly slower for large datasets.

4. **Optimized C Implementation:**

* NumPy: NumPy is implemented in C, providing a significant performance boost over pure Python implementations.

* Python Lists: Python lists are implemented in Python, which can be slower for numerical operations.

* Real-world Performance Implications: To illustrate the performance differences, consider a simple example:

In [11]:
import numpy as np
import time

# Create large arrays
N = 1000000
arr_np = np.random.rand(N)
arr_py = list(arr_np)

# Time a simple operation (e.g., summing elements)
start_np = time.time()
sum_np = np.sum(arr_np)
end_np = time.time()

start_py = time.time()
sum_py = sum(arr_py)
end_py = time.time()

print("NumPy time:", end_np - start_np)
print("Python list time:", end_py - start_py)

NumPy time: 0.0014405250549316406
Python list time: 0.05664634704589844


In this example, NumPy's vectorized operations will significantly outperform Python's loop-based approach, especially for large values of N.

In conclusion:

NumPy arrays provide a powerful and efficient tool for numerical computations in Python. By leveraging homogeneous data types, contiguous memory layout, vectorized operations, and optimized C implementation, NumPy enables you to perform large-scale numerical operations significantly faster than with standard Python lists.

#### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Ans-7. **vstack() and hstack() in NumPy**

NumPy provides two essential functions for stacking arrays: vstack() and hstack(). These functions are used to combine arrays along specific axes.

1. vstack()

* Vertical Stacking: This function stacks arrays vertically, meaning it adds rows.

* Syntax: np.vstack((array1, array2, ...))

In [12]:
#Example:

import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

result = np.vstack((array1, array2))
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2. hstack()

* Horizontal Stacking: This function stacks arrays horizontally, meaning it adds columns.

* Syntax: np.hstack((array1, array2, ...))

In [13]:
#Example:

import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = np.hstack((array1, array2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


**Key Points:**

1. Array Shapes: The arrays being stacked must have compatible shapes for the operation to be successful. For vstack(), the number of columns must be the same, and for hstack(), the number of rows must be the same.

2. Data Types: The data types of the arrays being stacked should ideally be the same. NumPy will attempt to find a common data type if necessary.

3. Performance: NumPy's optimized implementation of these functions ensures efficient stacking operations, even for large arrays.

* By understanding and effectively using vstack() and hstack(), you can efficiently combine and manipulate arrays in various numerical computations.

#### 8.  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Ans-8. **fliplr() and flipud() in NumPy**

NumPy provides two functions, fliplr() and flipud(), for flipping arrays along specific axes.

1. fliplr()

* Flips the array left-right.

* Axis: Flips along the second axis (columns).

In [14]:
#Example:

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flipped_arr = np.fliplr(arr)
print(flipped_arr)

[[3 2 1]
 [6 5 4]]


2. flipud()

* Flips the array up-down.

* Axis: Flips along the first axis (rows).

In [15]:
#Example:

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flipped_arr = np.flipud(arr)
print(flipped_arr)

[[4 5 6]
 [1 2 3]]


**Effects on Different Array Dimensions:**

1. **1D Arrays:** Both fliplr() and flipud() reverse the order of elements in a 1D array.

2. **2D Arrays:**
fliplr(): Reverses the order of columns.
flipud(): Reverses the order of rows.

3. **Higher-Dimensional Arrays:**
Both functions flip along the specified axis. For instance, in a 3D array, fliplr() flips along the second axis (columns of each 2D slice), and flipud() flips along the first axis (rows of each 2D slice).

####Key Points:

* Both fliplr() and flipud() return a new array, leaving the original array unchanged.

* These functions are useful for various image processing, signal processing, and data manipulation tasks.

* By understanding their behavior, you can effectively manipulate arrays in NumPy to achieve desired results.

#### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans-9. **array_split() in NumPy**

The array_split() function in NumPy is a versatile tool for dividing an array into smaller sub-arrays along a specified axis. It's particularly useful when you want to break down large arrays into smaller, more manageable chunks.

In [16]:
#Basic usage:

import numpy as np

arr = np.arange(10)
split_arr = np.array_split(arr, 5)
print(split_arr)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


**Handling Uneven Splits:**

When the number of sections doesn't divide evenly into the array's length, array_split() handles the uneven distribution intelligently. It ensures that the resulting sub-arrays are as close to equal in size as possible.

In [17]:
#Example:

arr = np.arange(11)
split_arr = np.array_split(arr, 4)
print(split_arr)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10])]


As you can see, the first three sub-arrays have three elements each, while the last one has two. This is the most efficient way to split the array into four parts, ensuring minimal differences in size.

**Key Points:**

* Axis Specification: You can specify the axis along which to split the array using the axis parameter.

* Flexibility: array_split() is flexible and can handle various array shapes and splitting scenarios.
Uneven Splits: It handles uneven splits efficiently, ensuring fair distribution.

* Sub-array Creation: The function returns a list of sub-arrays, each of which is a NumPy array itself.

* By understanding the functionality of array_split(), you can effectively divide large arrays into smaller, more manageable chunks for various data processing and analysis tasks.

#### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Ans-10. **Vectorization and Broadcasting in NumPy**

NumPy is renowned for its ability to perform efficient numerical computations on arrays. Two key concepts that contribute significantly to this efficiency are vectorization and broadcasting.

1. Vectorization

Vectorization involves performing operations on entire arrays element-wise, without the need for explicit loops. This is made possible by NumPy's optimized C-level implementation and the use of SIMD (Single Instruction, Multiple Data) instructions.


In [18]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
c = a + b  # Equivalent to [1+4, 2+5, 3+6]
print(c)  # Output: [5 7 9]

[5 7 9]


In this example, the addition operation is applied to corresponding elements of the arrays a and b simultaneously, resulting in a new array c. This vectorized approach is significantly faster than using a Python loop to iterate over each element.

2. **Broadcasting**

Broadcasting is a powerful feature that allows NumPy to perform operations on arrays with different shapes. The smaller array is "broadcast" or stretched to match the shape of the larger array, enabling element-wise operations.

In [19]:
#Example:

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Broadcasting to add a row vector to each row of a matrix
c = a + b
print(c)

[[11 22 33]
 [14 25 36]]


In this case, the 1D array b is broadcasted to match the shape of the 2D array a. Each element of b is added to the corresponding row of a.

**How Vectorization and Broadcasting Contribute to Efficiency**

* Optimized C Implementation: NumPy's core operations are implemented in optimized C code, which significantly outperforms pure Python loops.

* SIMD Instructions: Vectorization allows NumPy to take advantage of SIMD instructions, which can perform multiple operations simultaneously on multiple data elements.

* Reduced Overhead: By avoiding explicit loops, vectorization and broadcasting reduce the overhead of Python's interpreter.

* Memory Efficiency: NumPy arrays are stored in contiguous memory blocks, which improves cache locality and memory access patterns.

* By understanding and effectively utilizing vectorization and broadcasting, you can write efficient and concise NumPy code for a wide range of numerical computations.

# Practical Questions:

#### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [20]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(array)

# Interchange rows and columns (transpose)
array_transposed = array.T

print("\nTransposed array:")
print(array_transposed)

Original array:
[[84 45 71]
 [50 77 71]
 [98 40 67]]

Transposed array:
[[84 50 98]
 [45 77 40]
 [71 71 67]]


#### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [21]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array = np.arange(10)

print("Original 1D array:")
print(array)

# Reshape it into a 2x5 array
array_2x5 = array.reshape(2, 5)

print("\nReshaped 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array.reshape(5, 2)

print("\nReshaped 5x2 array:")
print(array_5x2)

Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [22]:
import numpy as np

# Create a 4x4 array with random float values
array = np.random.rand(4, 4)

print("Original array:")
print(array)

# Create a 6x6 array with zeros
array_with_border = np.zeros((6, 6))

# Place the original array in the center of the 6x6 array
array_with_border[1:5, 1:5] = array

print("\nArray with zero border:")
print(array_with_border)

Original array:
[[0.81669344 0.97333737 0.66356836 0.99131395]
 [0.39692455 0.29167097 0.1069661  0.23422888]
 [0.60748675 0.78657169 0.21206195 0.94054672]
 [0.10087685 0.63449027 0.58875676 0.14557233]]

Array with zero border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.81669344 0.97333737 0.66356836 0.99131395 0.        ]
 [0.         0.39692455 0.29167097 0.1069661  0.23422888 0.        ]
 [0.         0.60748675 0.78657169 0.21206195 0.94054672 0.        ]
 [0.         0.10087685 0.63449027 0.58875676 0.14557233 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [23]:
import numpy as np

array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


####5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [33]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Original array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Titlecase:", titlecase_arr)


Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']


#### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [34]:
import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Function to insert spaces between characters
def insert_spaces(word):
    return ' '.join(list(word))

# Apply the function to each element in the array
spaced_words = np.vectorize(insert_spaces)(words)

print("Original array:", words)
print("Spaced words array:", spaced_words)

Original array: ['python' 'numpy' 'pandas']
Spaced words array: ['p y t h o n' 'n u m p y' 'p a n d a s']


#### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [35]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

# Print the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [36]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


####9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.




In [37]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)


Random Integers:
 [731 524  74 743  77  72   4 638 948 120 132 185 625 364 261 319 851 503
 829 290  19 588 458 277 881 764 203 980  84 860 855 734 909 233 257 480
 852  47 564 674 547 496 795 313 312 766 161 461 828 181 600  19  16 121
 408 393 252 930 979 908 332 887 802 655 832 797  47 421 511 704 112 194
 330 545 311 813 159  66 151 845 437 936 932 618 703 932 835 426 469 836
 339   8 908 428 254 585  83 646 377 514]
Prime Numbers:
 [743, 503, 829, 19, 277, 881, 233, 257, 47, 547, 313, 461, 181, 19, 887, 797, 47, 421, 311, 151, 83]


#### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [38]:
import numpy as np

# Generate a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)

# Calculate weekly averages
week_1_avg = np.mean(daily_temperatures[0:7])
week_2_avg = np.mean(daily_temperatures[7:14])
week_3_avg = np.mean(daily_temperatures[14:21])
week_4_avg = np.mean(daily_temperatures[21:28])
week_5_avg = np.mean(daily_temperatures[28:30])  # Last few days

# Print the results
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("Weekly Averages:")
print("Week 1 Average:", week_1_avg)
print("Week 2 Average:", week_2_avg)
print("Week 3 Average:", week_3_avg)
print("Week 4 Average:", week_4_avg)
print("Week 5 Average:", week_5_avg)


Daily Temperatures for the Month:
 [21 18 32 23 18 22 15 33 26 30 24 21 29 33 29 20 31 26 31 22 16 31 22 31
 32 29 27 17 33 33]
Weekly Averages:
Week 1 Average: 21.285714285714285
Week 2 Average: 28.0
Week 3 Average: 25.0
Week 4 Average: 27.0
Week 5 Average: 33.0
